language: python
python:
  - "3.6"

branches:
  only:
  - master

install:
- pip install pylint
- pip install -r requirements.txt

script:
- export WONT_FIX=invalid-name,bad-indentation,too-many-lines,too-many-instance-attributes
- export MAYBE_LATER=line-too-long,missing-docstring,bad-continuation,bad-whitespace
- pylint --disable=$WONT_FIX,$MAYBE_LATER *.py
